### ISSUE TITLE
`ProgressMaterialButton`

### ISSUE THREAD

**Issue by msasikanth** [simpledotorg/simple-android#1374]
# Problem

At times we need to show the progress bar for the `MaterialButton` before enable/disable it. In order to do that right now, we are manually triggering the state changes in the screen we need this behaviour. 

It would be better we if can extract these things into its own `View`, which will improve the reusability of these kinds of behaviours. The reason why I didn't went with a layout file and compound view approach is that we have to handle theming all the attrs for `MaterialButton`.

# Proposal

We have to use a custom view, We cannot directly place the `ProgressBar` inside the `MaterialButton` because it's just a `TextView`. So we create custom `FrameLayout` that will add `MaterialButton` & `ProgressBar` internally.

```kotlin
class ProgressMaterialButton @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet? = null,
  defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr) {

  enum class ButtonState {
    InProgress, Enabled, Disabled
  }

  companion object {
    private val BUTTON_STYLES = arrayOf(
      R.attr.materialButtonStyle,
      R.attr.materialButtonOutlinedStyle
    )
  }

  private var buttonState = ButtonState.InProgress
  private var buttonText: String? = null
  private var buttonIcon: Drawable? = null

  private val materialButton: MaterialButton
  private val progress: ProgressBar

  init {
    val typedArray = context.obtainStyledAttributes(attrs, R.styleable.ProgressMaterialButton)

    buttonText = typedArray.getString(R.styleable.ProgressMaterialButton_android_text)
    buttonIcon = typedArray.getDrawable(R.styleable.ProgressMaterialButton_icon)
    val materialButtonStyleAttr = BUTTON_STYLES[typedArray.getInt(R.styleable.ProgressMaterialButton_progressButtonStyle, 0)]
    val progressColor = typedArray.getColor(R.styleable.ProgressMaterialButton_progressColor, 0)

    materialButton = createButton(context, attrs, materialButtonStyleAttr)
    progress = createProgress(context, attrs).apply {
      isIndeterminate = true

      // We are setting the translationZ to set the view on top of the material button,
      // since material button has elevation with out the translationZ of progress bar it
      // will be behind it.
      translationZ = 8.dp.toFloat()

      indeterminateTintList = ColorStateList.valueOf(progressColor)
    }

    addView(materialButton)
    addView(progress)

    setButtonState(buttonState)

    progress.updateLayoutParams<LayoutParams> {
      height = 32.dp
      gravity = Gravity.CENTER
    }

    typedArray.recycle()

    clipToPadding = false
  }

  override fun setOnClickListener(l: OnClickListener?) {
    @Suppress("LABEL_NAME_CLASH")
    materialButton.setOnClickListener {
      if (buttonState != ButtonState.Enabled) {
        return@setOnClickListener
      }
      l?.onClick(this)
    }
  }

  private fun createButton(context: Context, attrs: AttributeSet?, @AttrRes materialButtonStyleAttr: Int): MaterialButton {
    return MaterialButton(context, attrs, materialButtonStyleAttr)
  }

  private fun createProgress(context: Context, attrs: AttributeSet?): ProgressBar {
    return ProgressBar(context, attrs)
  }

  fun setButtonState(buttonState: ButtonState) {
    when (buttonState) {
      ButtonState.InProgress -> {
        progress.visibility = View.VISIBLE
        materialButton.icon = null
        materialButton.text = null
        materialButton.isEnabled = true
      }
      ButtonState.Enabled -> {
        progress.visibility = View.GONE
        materialButton.icon = buttonIcon
        materialButton.text = buttonText
        materialButton.isEnabled = true
      }
      ButtonState.Disabled -> {
        progress.visibility = View.GONE
        materialButton.icon = buttonIcon
        materialButton.text = buttonText
        materialButton.isEnabled = false
      }
    }
    this.buttonState = buttonState
  }
}
```

## Problems with this approach
- We have to copy some/all attrs from the `MaterialButton` to our `attrs.xml` file in order to let the auto-complete work. _(We have to copy attrs for `ProgressBar` if we need the auto-complete for it as well)_
- Applying style to `MaterialButton` seems to be problematic, we cannot directly apply the style to the custom `View` because it would apply it for the underlying `FrameLayout` & `ProgressBar` as well. Adding a custom attr to get the theme for `MaterialButton` and using `ContextThemeWrapper` when creating the `MaterialButton` doesn't seem to work as well. So it's something we need to figure out or keep in mind.

**Comment by vinaysshenoy** [comment]
As you already mentioned, a problem with this approach is that we would need to copy all attrs from `MaterialButton` and `ProgressBar` to get auto complete. In addition, we will need to keep this updated whenever new attrs are added, which is additional maintenance effort.

Instead of switching between different views, how about extending `MaterialButton` and changing the text, background, and colours based on the states? Maybe it might be worth discussing with the design team what a "progress" button would look like (ideally the behaviour should be similar to the "Contact Doctor" button we have now) and take a call on this.

**Comment by vinaysshenoy** [comment]
We could potentially add custom attrs specific to this:

```xml
app:failureStateText="@string/"
app:failureBackgroundDrawable=""
app:failureTextAppearance=""
app:progressStateText=""
...
```

**Comment by msasikanth** [comment]
> As you already mentioned, a problem with this approach is that we would need to copy all attrs from `MaterialButton` and `ProgressBar` to get auto complete. In addition, we will need to keep this updated whenever new attrs are added, which is additional maintenance effort.
> 
> Instead of switching between different views, how about extending `MaterialButton` and changing the text, background, and colours based on the states? Maybe it might be worth discussing with the design team what a "progress" button would look like (ideally the behaviour should be similar to the "Contact Doctor" button we have now) and take a call on this.

One of the reasons why I didn't extend the `MaterialButton` is it's not possible to place a `ProgressBar` inside the button since it's a `TextView`. Unless we remove the `ProgressBar` entirely to represent the progress state I am not sure how we can do this.

One random thought I have is to use custom progress drawable in place of the button icon. That way all we have to do is to replace the icon during the state changes and hide the text if it's just in progress mode, WDYT?

**Comment by vinaysshenoy** [comment]
Yes, that's what I meant. Use a `ProgressDrawable` instead of a `ProgressBar` widget.

**Comment by msasikanth** [comment]
I talked to Mahima about this, we can perhaps use an `AnimatedVectorDrawable` to indicate a loading state. The reason we are wary about using text to indicate loading state is it might get cut off when DPI high, so we think icon might be a good idea to go with.

**Comment by msasikanth** [comment]
Also, there doesn't seem to be a straight forward way of implementing `ProgressDrawable`. I will continue looking into it.

**Comment by vinaysshenoy** [comment]
> I talked to Mahima about this, we can perhaps use an `AnimatedVectorDrawable` to indicate a loading state. The reason we are wary about using text to indicate loading state is it might get cut off when DPI high, so we think icon might be a good idea to go with.

This is a good idea. Perhaps we can set it down as part of design principles for the progress buttons that we will add.

- All states must have the same width
- Progress states do not have any text, only a progress drawable.
- ?

**Comment by vinaysshenoy** [comment]
> Also, there doesn't seem to be a straight forward way of implementing `ProgressDrawable`. I will continue looking into it.

I vaguely recall doing something in one of my previous jobs. Maybe we can look at the animated vector resource which the framework `ProgressBar` uses and just reuse that?

**Comment by vinaysshenoy** [comment]
It should also be fairly easy to get an animated vector ourselves.

**Comment by msasikanth** [comment]
> > Also, there doesn't seem to be a straight forward way of implementing `ProgressDrawable`. I will continue looking into it.
> 
> I vaguely recall doing something in one of my previous jobs. Maybe we can look at the animated vector resource which the framework `ProgressBar` uses and just reuse that?

`ProgressBar` uses a drawable created programmatically iirc. But I will just go with creating a custom `AnimatedVectorDrawable` first.

**Comment by vinaysshenoy** [comment]
> > > Also, there doesn't seem to be a straight forward way of implementing `ProgressDrawable`. I will continue looking into it.
> > 
> > 
> > I vaguely recall doing something in one of my previous jobs. Maybe we can look at the animated vector resource which the framework `ProgressBar` uses and just reuse that?
> 
> `ProgressBar` uses a drawable created programmatically iirc. But I will just go with creating a custom `AnimatedVectorDrawable` first.

Were we able to see any *progress* (sorry!) on this? If using an animated vector works, we should go ahead and make this change once Telemed v2 is done. This would be useful in a few other screens as well (patient registration, for one).

**Comment by msasikanth** [comment]
> Were we able to see any _progress_ (sorry!) on this? If using an animated vector works, we should go ahead and make this change once Telemed v2 is done. This would be useful in a few other screens as well (patient registration, for one).

I have tried it with [CircularProgressDrawable](https://developer.android.com/reference/androidx/swiperefreshlayout/widget/CircularProgressDrawable?authuser=1) which doesn't seem to work properly. Once Telemed v2 is done, I will create a new AVD or recently material library update introduced `ProgressIndicator`, in the design docs they showed using it with buttons, so I will give it a try as well.

**Comment by vinaysshenoy** [comment]
Nice!

**Comment by msasikanth** [comment]
_Progress_ (😂 ) on the button. I have found a progress AVD that is already [made](https://github.com/alexjlockwood/adp-delightful-details/blob/master/app/src/main/res/drawable/avd_progress_indeterminate_circular.xml). Everything seems to work fine, one thing we might need to add is saving the state of the `ButtonState`.

```kt
class ProgressMaterialButton(
  context: Context,
  attrs: AttributeSet? = null
) : MaterialButton(context, attrs) {

  enum class ButtonState {
    InProgress, Enabled, Disabled
  }

  private var buttonState = ButtonState.InProgress
  private var buttonText: String? = null
  private var buttonIcon: Drawable? = null
  private var buttonIconGravity: Int? = null

  private var progressDrawable = AnimatedVectorDrawableCompat.create(context, R.drawable.avd_progress)

  private val progressAvdCallback = object : Animatable2Compat.AnimationCallback() {
    override fun onAnimationEnd(drawable: Drawable?) {
      super.onAnimationEnd(drawable)
      progressDrawable?.start()
    }
  }

  init {
    val typedArray = context.obtainStyledAttributes(attrs, R.styleable.ProgressMaterialButton)

    buttonText = typedArray.getString(R.styleable.ProgressMaterialButton_android_text)
    buttonIcon = typedArray.getDrawable(R.styleable.ProgressMaterialButton_icon)
    buttonIconGravity = iconGravity

    setButtonState(buttonState)
    typedArray.recycle()
  }

  override fun onAttachedToWindow() {
    super.onAttachedToWindow()
    progressDrawable?.run {
      registerAnimationCallback(progressAvdCallback)
      start()
    }
  }

  override fun onDetachedFromWindow() {
    super.onDetachedFromWindow()
    progressDrawable?.unregisterAnimationCallback(progressAvdCallback)
  }

  fun setButtonState(buttonState: ButtonState) {
    when (buttonState) {
      ButtonState.InProgress -> {
        isEnabled = true
        isClickable = false
        icon = progressDrawable
        text = null
        iconGravity = ICON_GRAVITY_TEXT_START
      }
      ButtonState.Enabled -> {
        isEnabled = true
        isClickable = true
        icon = buttonIcon
        text = buttonText
        if (buttonIconGravity != null) {
          iconGravity = buttonIconGravity!!
        }
      }
      ButtonState.Disabled -> {
        isEnabled = false
        icon = buttonIcon
        text = buttonText
        if (buttonIconGravity != null) {
          iconGravity = buttonIconGravity!!
        }
      }
    }
    this.buttonState = buttonState
  }
}
```

**Comment by vinaysshenoy** [comment]
This looks good. Let's make a ticket for implementing this and get to it once Telemed v2 is complete.

**Comment by msasikanth** [comment]
Tracking the story here: https://www.pivotaltracker.com/story/show/173283089
