### ISSUE TITLE
Integrate sentry

### ISSUE THREAD

**Issue by dvenkatr** [simpledotorg/simple-android#19]
- [x] Integrate Android app with Sentry SDK (for fatals)
- [x] Provide Sentry configuration and secrets from Bitrise while generating builds
- [x] Enable multidex
- [x] Sanity check that everything here is done?

**Comment by pratul** [comment]
@timcheadle To do this, I need the "Sentry DSN (client key)" so I can configure the SDK on Android. More information here: https://docs.sentry.io/clients/java/modules/android/

Saket and I will also need access to the sentry.io dashboard.
