### ISSUE TITLE
Setting up a regression test suite for meeting performance goals

### ISSUE THREAD

**Issue by vinaysshenoy** [simpledotorg/simple-android#3329]
# The Problem
Simple is a client-side SQL heavy app. Over the last couple of years, the data in production has grown exponentially. Manually verifying the performance of all the user flows for every release is not feasible at our scale, so we typically don't end up realizing that some changes we made have caused a performance issue until it goes out to production and we start getting reports from the field.

# Goal
We need a way to automatically track the performance of important database queries over time and set up automated alerts when a regression happens.

# Approach
The overall approach would require us to set up three things:

1. A benchmark test suite on the Android codebase. This would be separate from the integration test suite that we already have, and will run against data selected from the `SANDBOX` environment, with a predefined scale of data comparable to larger datasets we have in `PRODUCTION`.
2. A tool to which we can report the performance metrics of the test suite we are running and visualize this over time.
3. Alerts of some kind which can send notifications (Slack, E-mail) to the team whenever a regression is detected.

### Filtering tests between CI and benchmark
The [AndroidJUnitRunner](https://developer.android.com/reference/androidx/test/runner/AndroidJUnitRunner) has a mechanism for dynamically deciding which tests to run using a [JUnit Filter](https://junit.org/junit4/javadoc/4.12/org/junit/runner/manipulation/Filter.html).

We can use this in conjunction with a custom annotation, say, `@BenchmarkTest`, in order to dynamically decide which tests to run depending on whether we are running in benchmark mode or CI mode.

### Measuring benchmark timings
Running tests for collecting performance metrics are a bit different than running tests which validate behavior. What we need to do here is run each test a fixed number of times, and then collect the median timings of the individual runs and use this for reporting. This ensures that timing spikes are smoothed out and regressions are actually due to changes that have been introduced and not due to one-off things that might be triggered behind the scenes.

In order to achieve this, we can add a custom [TestRule](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestRule.html) that will rerun these tests, collect timings, and send them off to our visualization tool.

### Setting up benchmark data
We normally run our integration test suite against ephemeral Heroku instances that are started from a clean slate. For the purposes of the performance regression test suite, however, what we need is to set up the app with a local database that is comparable to a large dataset from `PRODUCTION`.

What we will do, is whenever we start a test run in benchmark mode, we will login as a predefined user on the `SANDBOX` environment and sync all data for that user to the device first. This will be a one-time thing done before any of the tests are run, and we will use this database to run all the benchmark tests.

One caveat here is that if we are benchmarking operations that modify the dataset (ex: `INSERT` or `UPDATE` queries), then that will result in the dataset changing between test runs which is not ideal. We would need a mechanism to backup and restore the dataset without needing to sync from the server all over again.

## Reporting tool and alerts
On the server side, we use [Datadog](https://www.datadoghq.com/) to track performance metrics across the system and set up alerts on performance issues. Datadog has an [Android SDK](https://docs.datadoghq.com/real_user_monitoring/android/), which we can use in our tests to push this timing information there.

Once we have the information in Datadog, setting up email or Slack notifications on performance regressions is fairly straightforward since Datadog has in-built support for them.

## Sample
We did a quick research spike of what this entire setup would look like, and this can be found at [spike/db-performance-profiling](https://github.com/simpledotorg/simple-android/tree/spike/db-performance-profiling).

# Potential Issues
- We require both a custom annotation as well as a separate test rule to be applied to a test class in order for the complete reporting pipeline to work. This might be prone to human error by forgetting to add the test rule to a benchmark test (and vice versa). We have a couple of options to address this:
  - Add something like a Lint check for verifying that any test class with `@BenchmarkTest` applied also has a `@BenchmarkRule` added as a test rule.
  - Create a base class like `BaseBenchmarkTest`, apply both the annotation and the test rule to it and have all the benchmark tests inherit from this type.

**Comment by vinaysshenoy** [comment]
> # The Problem
> 
> Simple is a client-side SQL heavy app. Over the last couple of years, the data in production has grown exponentially. Manually verifying the performance of all the user flows for every release is not feasible at our scale, so we typically don't end up realizing that some changes we made have caused a performance issue until it goes out to production and we start getting reports from the field.
> # Goal
> 
> We need a way to automatically track the performance of important database queries over time and set up automated alerts when a regression happens.
> # Approach
> 
> The overall approach would require us to set up three things:
> 
>     1. A benchmark test suite on the Android codebase. This would be separate from the integration test suite that we already have, and will run against data selected from the `SANDBOX` environment, with a predefined scale of data comparable to larger datasets we have in `PRODUCTION`.
> 
>     2. A tool to which we can report the performance metrics of the test suite we are running and visualize this over time.
> 
>     3. Alerts of some kind which can send notifications (Slack, E-mail) to the team whenever a regression is detected.
> 
> 
> ## Benchmark Test Suite
> ### Filtering tests between CI and benchmark
> 
> The [AndroidJUnitRunner](https://developer.android.com/reference/androidx/test/runner/AndroidJUnitRunner) has a mechanism for dynamically deciding which tests to run using a [JUnit Filter](https://junit.org/junit4/javadoc/4.12/org/junit/runner/manipulation/Filter.html).
> 
> We can use this in conjunction with a custom annotation, say, `@BenchmarkTest`, in order to dynamically decide which tests to run depending on whether we are running in benchmark mode or CI mode.
> ### Measuring benchmark timings
> 
> Running tests for collecting performance metrics are a bit different than running tests which validate behavior. What we need to do here is run each test a fixed number of times, and then collect the median timings of the individual runs and use this for reporting. This ensures that timing spikes are smoothed out and regressions are actually due to changes that have been introduced and not due to one-off things that might be triggered behind the scenes.
> 
> In order to achieve this, we can add a custom [TestRule](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestRule.html) that will rerun these tests, collect timings, and send them off to our visualization tool.
> ### Setting up benchmark data
> 
> We normally run our integration test suite against ephemeral Heroku instances that are started from a clean slate. For the purposes of the performance regression test suite, however, what we need is to set up the app with a local database that is comparable to a large dataset from `PRODUCTION`.
> 
> What we will do, is whenever we start a test run in benchmark mode, we will login as a predefined user on the `SANDBOX` environment and sync all data for that user to the device first. This will be a one-time thing done before any of the tests are run, and we will use this database to run all the benchmark tests.
> 
> One caveat here is that if we are benchmarking operations that modify the dataset (ex: `INSERT` or `UPDATE` queries), then that will result in the dataset changing between test runs which is not ideal. We would need a mechanism to backup and restore the dataset without needing to sync from the server all over again.
> ## Reporting tool and alerts
> 
> On the server side, we use [Datadog](https://www.datadoghq.com/) to track performance metrics across the system and set up alerts on performance issues. Datadog has an [Android SDK](https://docs.datadoghq.com/real_user_monitoring/android/), which we can use in our tests to push this timing information there.
> 
> Once we have the information in Datadog, setting up email or Slack notifications on performance regressions is fairly straightforward since Datadog has in-built support for them.
> # Potential Issues
> 
>     * We require both a custom annotation as well as a separate test rule to be applied to a test class in order for the complete reporting pipeline to work. This might be prone to human error by forgetting to add the test rule to a benchmark test (and vice versa). We have a couple of options to address this:
>       
>       * Add something like a Lint check for verifying that any test class with `@BenchmarkTest` applied also has a `@BenchmarkRule` added as a test rule.
>       * Create a base class like `BaseBenchmarkTest`, apply both the annotation and the test rule to it and have all the benchmark tests inherit from this type.

**Comment by msasikanth** [comment]
The proposal is looking good @vinaysshenoy . Having a base class for benchmark tests seems the easiest option, compared to having a lint rule for it.

**Comment by Honey14** [comment]
Looks great, a few questions to understand the approach better:
* Are real world app performance tests called benchmark tests?
* Under setting up benchmark data, `INSERT AND UPDATE` are going to happen regardless, because both of these are a huge part. Why is syncing again not ideal? The dataset will run all over again after syncing and that is a problem, why?
* If we backup and restore the dataset with no sync, are we sure we'll never receive a regression with syncing after data update because with the current approach this use case will not be included

**Comment by vinaysshenoy** [comment]
> Looks great, a few questions to understand the approach better:
> 
>     * Are real world app performance tests called benchmark tests?

Benchmarking is typically used in the industry to test performance of libraries, frameworks, etc. Just following that convention here.

>     * Under setting up benchmark data, `INSERT AND UPDATE` are going to happen regardless, because both of these are a huge part. Why is syncing again not ideal? The dataset will run all over again after syncing and that is a problem, why?

Syncing data from Sandbox will take a lot of time (~30m), so ideally we don't want to do it over and over again for every test. Backing up and restoring the data between test runs will be faster.

>     * If we backup and restore the dataset with no sync, are we sure we'll never receive a regression with syncing after data update because with the current approach this use case will not be included

In the sense? The regression is something we track not over a single test run, but over multiple test runs. We would want to see degraded performance of a query over a couple of days along with a significant difference in query performance before we label it as a regression. I am not sure if you were referring to something else.

**Comment by Honey14** [comment]
The second answer clarifies it, thanks.
