### ISSUE TITLE
[IMPROVEMENT] Use date picker dialog for entering date of birth. 

### ISSUE THREAD

**Issue by divyanshub024** [simpledotorg/simple-android#337]
Using date picker dialog will be much easy to enter date for the user. And it will also stop user entering a wrong date format.

**Comment by saket** [comment]
Date pickers look nice, but typing date of births is much faster than using a multi-step GUI. Quoting our designer, @akshayverma1's words:

> Date pickers are too slow. We’ve tested this already and the text field works better for everyday use. Had this been a one off interaction that the users were not using regularly, a date picker would have been a better choice. We should totally build in some automatic error correction in the text based date input though.

**Comment by saket** [comment]
Thanks Divyanshu. We understand that date pickers look nicer and enforce the format, but typing date of births is much faster than using a multi-step GUI. Quoting our designer, @akshayverma1's words:

> Date pickers are too slow. We’ve tested this already and the text field works better for everyday use. Had this been a one off interaction that the users were not using regularly, a date picker would have been a better choice. We should totally build in some automatic error correction in the text based date input though.

**Comment by divyanshub024** [comment]
ok, Now after reading @akshayverma1's words I also feel that datepicker won't be good for everyday use.
