### ISSUE TITLE
Admin can create Facility

### ISSUE THREAD

**Issue by dvenkatr** [simpledotorg/simple-android#41]
## Bugs

- [x] editing a user from a facility's page returns a 404 because it links to protocol drugs (see detailed explanation below)
- [x] column rendering bug listed below

**Comment by deobald** [comment]
Small rendering bug: List facilities mis-aligns the columns and their content.
![screen shot 2018-06-13 at 16 58 45](https://user-images.githubusercontent.com/20282/41348735-3673f98c-6f2b-11e8-9671-8d2b7520cb62.png)

**Comment by deobald** [comment]
QA steps for @timcheadle and @terrycullen : 

1. Visit the integration server at http://13.127.130.247 

2. Log in with the username & password I've DM'd you

3. By default, you are taken to the `Facilities` UI at http://13.127.130.247/admin/facilities ... you can list, create, update, and delete Facilities here. Play this with UI and post bugs and comments on this card, tagging @ssrihari and @govindkrjoshi so they can quickly correct it.

**Comment by deobald** [comment]
@ssrihari @govindkrjoshi @timcheadle  There's another small bug on `Facility#show`: Click a `User#edit` link from the Users list; you'll get a 404 because it accidentally links to `ProtocolDrug#edit`.

**Comment by terrycullen** [comment]
there is no auto fill because we dont know the hierarchies (meaning, we dont have access to an MFR so i have to fill in everything?

**Comment by terrycullen** [comment]
the auto fill under name - seems to revert to the person signed in (i assume); while it may seem obvious that it should be the facility name, i wonder if it is.. maybe people will think it is their name??

**Comment by terrycullen** [comment]
is facility type a constrained list (limited options)? if so, can we make those options evident?

**Comment by terrycullen** [comment]
is PIN always a numeric? can we force numerics if that is the case

**Comment by terrycullen** [comment]
can country default

**Comment by terrycullen** [comment]
is it obvious what is optional and what isn't? village is optional/district isn't?

**Comment by ssrihari** [comment]
Thanks for the feedback, and suggestions @terrycullen. I've fixed them now, will move this card back to QA once it is deployed to staging.

- Autofills are dictated by the user's browser, and there isn't a (effective) way to disable it, or modify it per field.
- Added a default country: "India"
- Added a numericality validation for PIN
- Added "required" tags to the fields that are required (name, district, state, and country). Also added a red asterisk for what's required.
