### ISSUE TITLE
Bitrise link is not working

### ISSUE THREAD

**Issue by humazed** [simpledotorg/simple-android#413]
https://app.bitrise.io/app/db9b195f645cfed7#/builds_ 
is leading to 404 page

**Comment by saket** [comment]
That's probably working as expected. Our Bitrise dashboard isn't public so you won't be able to access the link.

**Comment by humazed** [comment]
okay, so the Bitrise for the team only.

but why it's the case won't making it public help someone curious or potential contributor to try the app since it's not on play store.
I don't see any harm in doing so.

**Comment by saket** [comment]
Totally agree with that. There's no point in keeping our Bitrise builds private when the project is open source. It's just that we haven't looked into this yet. I'll bring this up in office.

**Comment by saket** [comment]
Adding @pratul to this conversation

**Comment by pratul** [comment]
We've removed the Bitrise link (because Bitrise is used to generate builds only for internal use). Please feel free to build your own APK (using the README instructions) if you want to give the project a spin.
