### ISSUE TITLE
Switch to using App Bundle format for APK to reduce install file size 

### ISSUE THREAD

**Issue by pratul** [simpledotorg/simple-android#498]
See https://developer.android.com/platform/technology/app-bundle/ for more details.

**Comment by Hackertronix** [comment]
Hi @pratul 

I want to take a shot at this! But I need a bit more clarity on what would you be expecting in the PR 😄

**Comment by pratul** [comment]
@hackertronix we're discussing this internally and should have some updates in the next few days.

**Comment by vinaysshenoy** [comment]
Completed in #1362.
