### ISSUE TITLE
Gzip request bodies of network calls in the app

### ISSUE THREAD

**Issue by pratul** [simpledotorg/simple-android#499]
Gzip-d response bodies from the API already happens seamlessly. However, gzipping request bodies can reduce our data consumption significantly as well. From my limited research, the size of the bodies can be reduced by ~3x. 

More details here: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/RequestBodyCompression.java

**Comment by SubhrajyotiSen** [comment]
This can be resolved by using the `GzipRequestInterceptor` interceptor from https://square.github.io/okhttp/interceptors/#rewriting-requests right?

Is this still up for grabs?

**Comment by pratul** [comment]
CC @sanchita

**Comment by benryder1988** [comment]
Hi @pratul , is this Gzip Request improvement still open? I was thinking of taking a look at it if it's still required

**Comment by vinaysshenoy** [comment]
@SubhrajyotiSen @benryder1988 Thanks for offering to pick this up, apologies for taking this long to respond. We picked this up ourselves recently and ended up completing it in https://github.com/simpledotorg/simple-android/pull/2870.
