### ISSUE TITLE
If the process restarts while a registration is happening, the app crashes

### ISSUE THREAD

**Issue by pratul** [simpledotorg/simple-android#500]
Consider the following scenario:
1. The user starts registration
1. Before completing the registration process (requesting OTP after selecting a facility), they background the app for some reason
1. While the app is in background, the system kills the app process
1. When the app resumes, it restarts the app with the intermediate screen that was present
1. When resuming the registration flow, the app crashes

This is because the `OngoingRegistrationEntry` is stored as a transient property in `UserSession` and is not maintained across process restarts. We need to fix this by either making it a `SharedPreference` or store it in the database.

**Comment by vinaysshenoy** [comment]
Fixed now while we migrated the registration screens to Mobius.
