### ISSUE TITLE
Nurse can record Prescribed Drugs

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#52]
## As a ... I can ... So that ...

As a nurse, after recording their BP, I can record the patient's prescribed drugs according to the state protocol.

- [x] Show prescriptions under the current protocol
- [x] Save user selections
- [x] Show custom prescriptions
- [x] Add custom prescriptions
- [x] Support deletion of prescriptions

## Bugs

- [x] P0 After entering BP, then tap "add medicine", then tapping medicine/dose, then hit back arrow, BP keyboard pops back up
- [ ] P0 In some cases, 2 dosages are selected for the same drug (example: https://vitalstrat.slack.com/files/UAKE25198/FBCLDE4GZ/img_20180625_092427_963.jpg)
- [x] P1 When "add another medicine" entry is up, add an overlay to obfuscate the background
- [x] P1 If patient doesn't have any meds, the button should not say "UPDATE", but instead "ADD MEDICINES" (copy what's on [Zeplin](https://app.zeplin.io/project/5af2812b979d9e9123803ed8/screen/5b10e1c1517446700809fc5d)) 
- [x] P1 After entering drugs, the back button sometimes displays the BP entry screen instead of the Patient Summary screen
- [x] ~P1: (This may already be recorded) Add a new patient, BP pops up, enter BP, then tap "Add" on medicine, choose a medication, then hit back arrow in top left.... BP jumps up again. The BP shouldn't be triggered again.~
- [x] P1: Before medication is added the medicine button says "Add". It should say "Add medicines" as per Zeplin.
- [x] P2 There should be a SAVE/DONE button after medicines are added

**Comment by vikalp02** [comment]
P2: Here is the screen which shows a Toast whenever the medicines are added/updated.
[Zeplin Web](zpl.io/aRYG7dn)
