### ISSUE TITLE
Punjabi i18n translations

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#61]
- [x] evaluate `strings.xml` against Tethras' sample file (this works)
- [x] walk through a sample setup on Tethras.com
- [x] @dburka can set up a proper Tethras account using these instructions: https://docs.google.com/document/d/1y5iJ0GuUkXwlXRf8EiIRfuM_KEUhasIubuIZODdA1rg/edit?usp=sharing
- [x] Use the translations in the app
- [x] Sanity check with app in play store

**Comment by deobald** [comment]
- [ ] @pratul and @saket will fill in `strings.xml` when they next touch it
- [ ] grab https://github.com/resolvetosavelives/redapp/blob/master/app/src/main/res/values/strings.xml
- [ ] provide all english values to Punjabi Healthcare Professional for translation

**Comment by ssrihari** [comment]
List of all strings to translate: https://www.dropbox.com/sh/oihzg8atk2sjuc1/AADdOAmXFctEib7Q3qRvjyIfa?dl=0
