### ISSUE TITLE
Nurse can enter BP for new patient

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#8]
## As a ... I can ... So that ...
As a nurse after I have added a new patient, I can enter a patient's BP or skip to the next screen quickly

## Bugs
- [x] P0 Cursor needs to advance from systolic to diastolic inputs automatically. If the user types a 1 or a 2 in the systolic input, automatically jump after 3 characters. If the user types a 3-9 jump after 2 characters
- [x] P0 Disable rotation for now (it deletes whatever was typed in)
- [x] P1 After rotation, BP cannot be saved, and back button doesn't work
- [x] P1 When BP entry is up, add an overlay to obfuscate the background
- [x] P1 Before typing, there is only one dot displayed for systolic and one dot displayed for diastolic. It should be 3 dots and 3 dots.
- [x] P1 After entering initial BP, the "done" button does nothing. Clicking "done" should return the user to the home screen.
- [x] P1 After entering initial BP, sometimes the number pad displays over top of the `Systolic`/`Diastolic` fields so the user cannot see what she is entering.
- [x] Once a new patient has been saved, the BP entry sheet shows up every time the summary screen is resumed after coming back from prescribed drugs screen
- [x] P2 If you have a high BP then a normal BP, the normal BP shows up as red. (It re-renders as gray if you rotate)
- [x] ~P2: If you enter a high BP (e.g. 190/80) and then enter a normal BP (e.g. 135/60)... the normal BP is red. If you leave the patient record and come back to the same record, the color is correct (grey). — if this is the same as the above P2, please just check it off, @saket / @pratul .~

**Comment by deobald** [comment]
I've created [As a nurse, I cannot enter an invalid BP with the BP keyboard](https://github.com/resolvetosavelives/redapp/issues/79) which was carved out of this card. The keyboard rule-modelling, and corresponding QA, is non-trivial; the team can prioritize it separately.

**Comment by deobald** [comment]
My QA of this card is mostly questions so far:

- does `skip to the next screen quickly` just mean clicking outside the BP entry area to see the Patient Summary in behind?
- should I see a list of BPs on the Patient Summary or anywhere else yet? (I do not.)
- where will we capture the work associated with adding a new BP for an existing patient? I don't see a card on the wall for this and this card (#8) only describes entering BP for a new patient.

I entered a BP and it sync'd to the server (verified from the server console, since I can't see it in the UI) so the fundamentals of this card are definitely working.

**Comment by saket** [comment]
> does skip to the next screen quickly just mean clicking outside the BP entry area to see the Patient Summary in behind?

I think so, but might be a better idea to ask @dburka 

> should I see a list of BPs on the Patient Summary or anywhere else yet? (I do not.)

You will, once the patient summary screen is ready. The screen behind the BP sheet is the summary screen, but it's empty right now.

> where will we capture the work associated with adding a new BP for an existing patient? I don't see a card on the wall for this and this card (#8) only describes entering BP for a new patient.

Yea the app currently does not show any feedback, but the patient summary screen behind will get updated when it's ready so you'll be able to see saved values.

**Comment by dburka** [comment]
> does skip to the next screen quickly just mean clicking outside the BP entry area to see the Patient Summary in behind?

@saket Yes, just tapping outside the BP entry area satisfies this task
