### ISSUE TITLE
Auto-deploy to play store from bitrise

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#98]
- [x] get api access 
- [x] follow instructions on [blog post](https://blog.bitrise.io/how-to-deploy-android-app-to-google-play-store)
- [x] change app name from "Simple Clinic" to just "Simple", everywhere
- [x] badge the staging app icon with "STAGING" so it's painfully obvious to the testing team which app they're touching

**Comment by timcheadle** [comment]
@ssrihari I added API access like it asked. Turns out this is where `Release manager` made sense.

![image](https://user-images.githubusercontent.com/612212/41692455-65a3ed36-74ce-11e8-8ea0-b47a027499b5.png)
